name: Test project

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Test project
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: "go.sum"
      - name: Run tests
        run: |
          task test
      - uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0
